"""Emits a runnable Playwright pytest regression test per Finding. Plan design:
"every confirmed bug becomes a permanent regression test."

Key design decision: a ReproStep's `ref` (e.g. "e3") is only meaningful when
re-resolved against a freshly-observed PageModel — it's not a CSS selector, it's an
ephemeral per-observation handle (see browser/observe.py). A naive script generator
would have to either bake in a guessed selector (fragile — the exact thing this
project's whole `ref` design exists to avoid) or re-implement ref resolution from
scratch. Instead, the generated script just re-uses analysis/replay.py's
already-proven mechanism: it embeds the Finding as data and calls
`replay_finding()`, asserting the bug no longer reproduces. This means the emitted
test's correctness is inherited from replay.py's own (already tested) logic rather
than needing a second independent implementation to keep in sync.

For `detector == "invariant"` findings specifically: the invariant CONFIG that
caught it (selectors, expression) isn't stored on the Finding itself — only the
invariant's *name* is recoverable from the title ("Invariant violated: {name}").
`emit_repro_script()` therefore takes the run's full invariant list and looks up the
matching one by name, embedding just that one config into the script. A finding for
an invariant that isn't in the list it's given emits a script with no invariants
configured — it will not be able to replay that specific finding, and the emitted
file says so in a comment rather than silently producing a script that can't work.
"""
from __future__ import annotations

import re
from pathlib import Path

from qaura.config import InvariantConfig
from qaura.reporting.models import Finding

# title/description come from the target app (console text, DOM text, an LLM triage
# note) or the target's own users, not from QAura — see FINDING below, where the same
# values are correctly !r-escaped as part of a Python literal. This docstring header
# used to interpolate them RAW into a `"""`-delimited string; a stray `"""` or
# trailing backslash in either produced a syntactically broken .py file, and content
# after a closing `"""` became executable module-level code. The header now carries
# only the finding id, which is UUID-derived and therefore already safe.
_TEMPLATE = '''"""Auto-generated by QAura from finding {finding_id}.

Regenerate: this file is derived from a Finding captured during a QAura run — edits
here will be lost if the same finding is re-emitted. To keep a fix, either resolve
the underlying bug (this test should then fail to reproduce and can be deleted or
kept as a permanent regression guard) or copy what you need into a hand-maintained test.

See FINDING.title / FINDING.description below for the actual bug details.
"""
from pathlib import Path

import pytest

from qaura.analysis.replay import replay_finding
from qaura.browser.driver import Driver
from qaura.config import InvariantConfig, QAuraConfig
from qaura.reporting.models import Finding, ReproStep

FINDING = Finding(
    id={finding_id!r},
    title={title!r},
    detector={detector!r},
    url={url!r},
    description={description!r},
    repro_steps=[
{repro_steps_literal}
    ],
)

{invariants_comment}INVARIANTS = [
{invariants_literal}
]

# Session the original run used; replaying a logged-in bug anonymously would never reproduce it
STORAGE_STATE = {storage_state!r}


@pytest.mark.asyncio
async def test_repro_{safe_id}():
    """Fails while the bug still reproduces; passes once it's fixed."""
    if STORAGE_STATE and not Path(STORAGE_STATE).exists():
        pytest.skip(f"session file {{STORAGE_STATE}} is missing; recapture it with qaura auth capture")
    async with Driver(headless=True) as driver:
        cfg = QAuraConfig(invariants=INVARIANTS)
        result = await replay_finding(driver, cfg, FINDING, attempts=1, storage_state_path=STORAGE_STATE)
    assert result.successes == 0, (
        f"Bug still reproduces: {{FINDING.title}} ({{result.rate_str}})"
    )
'''


def _safe_id(finding_id: str) -> str:
    """A finding id freshly generated by this run is UUID-derived and already safe
    (models.py:Finding.id), but RunReport.load_json() accepts any string from a
    report.json on disk — and `qaura report`/`qaura replay` take a user-supplied path
    to one. The old `.replace("-", "_").replace(" ", "_")` left `/`, `\\`, and `..`
    untouched, so a crafted or hand-edited report could write outside out_dir.
    Collapsing to a bounded identifier-safe string closes that and, as a side effect,
    guarantees `test_repro_{safe_id}` is always a valid Python function name."""
    safe = re.sub(r"[^A-Za-z0-9_]", "_", finding_id)
    return safe[:64] or "unknown"


def _find_invariant_for(finding: Finding, invariants: list[InvariantConfig]) -> InvariantConfig | None:
    if finding.detector != "invariant":
        return None
    name = finding.title.removeprefix("Invariant violated:").strip()
    return next((inv for inv in invariants if inv.name == name), None)


def _repro_step_literal(step) -> str:
    return (
        f"        ReproStep(description={step.description!r}, action_kind={step.action_kind!r}, "
        f"ref={step.ref!r}, value={step.value!r}, url_before={step.url_before!r}),"
    )


def _invariant_literal(inv: InvariantConfig) -> str:
    return (
        f"    InvariantConfig(name={inv.name!r}, description={inv.description!r}, "
        f"container_selector={inv.container_selector!r}, values={inv.values!r}, "
        f"expression={inv.expression!r}),"
    )


def render_repro_script(
    finding: Finding, invariants: list[InvariantConfig] | None = None, storage_state_path: str | None = None,
) -> str:
    invariants = invariants or []
    matched = _find_invariant_for(finding, invariants)

    if finding.detector == "invariant" and matched is None:
        comment = (
            "# NOTE: this is an 'invariant' finding but no matching InvariantConfig was\n"
            "# supplied when this script was generated — it cannot actually replay this\n"
            "# finding. Re-emit with the run's full invariant list.\n"
        )
    else:
        comment = ""

    invariants_literal = "\n".join(_invariant_literal(matched) for matched in ([matched] if matched else []))
    repro_steps_literal = "\n".join(_repro_step_literal(s) for s in finding.repro_steps)
    safe_id = _safe_id(finding.id)

    return _TEMPLATE.format(
        finding_id=finding.id, title=finding.title, detector=finding.detector,
        url=finding.url, description=finding.description,
        repro_steps_literal=repro_steps_literal or "        # (no repro steps captured)",
        invariants_comment=comment, invariants_literal=invariants_literal, safe_id=safe_id,
        storage_state=storage_state_path,
    )


def emit_repro_script(
    finding: Finding, out_dir: str | Path, invariants: list[InvariantConfig] | None = None,
    storage_state_path: str | None = None,
) -> Path | None:
    """Returns the written path, or None when there's nothing useful to generate: no
    repro_steps, or a detector replay can't re-check (a `flow` script would always pass,
    since replay never re-runs that detector). Not an error for the caller."""
    # Deferred: replay pulls in Playwright and every detector
    from qaura.analysis.replay import REPLAYABLE_DETECTORS

    if not finding.repro_steps or finding.detector not in REPLAYABLE_DETECTORS:
        return None
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    safe_id = _safe_id(finding.id)
    path = out_dir / f"test_repro_{safe_id}.py"
    path.write_text(render_repro_script(finding, invariants, storage_state_path), encoding="utf-8")
    return path
