"""Renders the proposed config as commented YAML.

pyyaml cannot emit comments and the annotations are the whole point of this file — a bare
`max_actions_per_run: 275` tells a reviewer nothing, while the same line above "25 per
distinct state, recon saw 11" tells them whether to trust it. So this module owns comment
and indent placement and hands every actual VALUE to yaml.safe_dump. Interpolating values
by hand would be the obvious shortcut and the wrong one: a selector like
[data-testid="cart-total"] and a description containing a colon both need real quoting
rules, and reimplementing those is how you ship a config file that won't parse.

ruamel.yaml would give round-trip comment support, but round-tripping only helps when
editing an existing document and everything here is generated from scratch — not worth a
new dependency for a feature we would not use.
"""
from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

import yaml

from qaura.init.candidates import CandidateVerdict

WRAP_WIDTH = 88


class ConfidenceLevel(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class Annotated:
    key: str
    value: Any
    confidence: ConfidenceLevel
    comment: str = ""
    subcomments: dict[str, str] = field(default_factory=dict)
    trailing_comment: str | None = None

    @property
    def commented_out(self) -> bool:
        """LOW confidence is always emitted commented out. A guess that has to be
        uncommented is a suggestion; a guess written live is a defect with a delay."""
        return self.confidence is ConfidenceLevel.LOW


@dataclass
class HeaderInfo:
    command: str
    version: str
    pages_visited: int
    distinct_states: int
    blocked_requests: int
    allowed_requests: int
    login_verdict: str
    authorization: str
    recon_digest: str
    llm_used: bool
    notes: list[str] = field(default_factory=list)


@dataclass
class ConfigProposal:
    header: HeaderInfo
    fields: list[Annotated]
    verdicts: list[CandidateVerdict] = field(default_factory=list)


def _comment_block(text: str, indent: str = "", bullet: str = "#   ") -> list[str]:
    out: list[str] = []
    for paragraph in text.split("\n"):
        if not paragraph.strip():
            continue
        wrapped = textwrap.wrap(paragraph, width=WRAP_WIDTH - len(indent) - len(bullet))
        out.extend(f"{indent}{bullet}{line}" for line in wrapped or [""])
    return out


def _dump(key: str, value: Any) -> str:
    return yaml.safe_dump(
        {key: value}, sort_keys=False, default_flow_style=False, allow_unicode=True, width=WRAP_WIDTH
    ).rstrip("\n")


def render_field(annotated: Annotated) -> str:
    lines = [f"# {annotated.key} — confidence: {annotated.confidence.value}"]
    if annotated.comment:
        lines.extend(_comment_block(annotated.comment))

    body = _dump(annotated.key, annotated.value)

    # Sub-key comments are interleaved by scanning the dumped block for each key at one
    # level of indent. Done on pyyaml's output rather than by building the YAML by hand,
    # so quoting stays pyyaml's problem.
    if annotated.subcomments:
        interleaved: list[str] = []
        for line in body.split("\n"):
            stripped = line.strip()
            for sub_key, sub_comment in annotated.subcomments.items():
                if stripped.startswith(f"{sub_key}:"):
                    indent = line[: len(line) - len(line.lstrip())]
                    interleaved.extend(_comment_block(sub_comment, indent=indent, bullet="# "))
                    break
            interleaved.append(line)
        body = "\n".join(interleaved)

    if annotated.commented_out:
        body = "\n".join(f"# {line}" if line.strip() else "#" for line in body.split("\n"))
        lines.append("# (commented out — low confidence, review before enabling)")

    lines.append(body)
    if annotated.trailing_comment:
        lines.append(annotated.trailing_comment)
    return "\n".join(lines)


def render_header(header: HeaderInfo) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    login_note = {
        "none": "No login wall detected.",
        "login_page": "A login page was seen.",
        "partial_wall": "PARTIAL login wall — some routes required a session.",
        "full_wall": "FULL login wall — almost everything required a session.",
    }.get(header.login_verdict, header.login_verdict)

    lines = [
        "# qaura.generated.yaml — a PROPOSED config. Not active until you adopt it.",
        "#",
        f"# Generated by: {header.command}",
        f"# qaura {header.version} · {stamp}",
        f"# Recon: {header.pages_visited} navigation(s), {header.distinct_states} distinct state(s),",
        f"#        {header.allowed_requests} request(s) allowed, {header.blocked_requests} blocked,",
        "#        GET/HEAD only.",
        f"# Auth:  {login_note}",
        f"# Digest: {header.recon_digest} — a hash of what recon saw. Two runs with the same",
        "#         digest observed the same site, so any difference came from the model.",
    ]
    if header.llm_used:
        lines.append("#         Invariant synthesis uses an LLM and is not reproducible run to run.")
    lines.append(f"# Scope: {header.authorization}")

    if header.notes:
        lines.append("#")
        for note in header.notes:
            lines.extend(_comment_block(note, bullet="# "))

    lines.extend([
        "#",
        "# Confidence legend:",
        "#   high   — directly observed or measured during recon, or a fixed safe constant",
        "#   medium — derived from what recon saw, by a rule with known failure modes",
        "#   low    — a pattern guess; emitted COMMENTED OUT, uncomment only after checking",
        "#",
        "# Fields not listed here (model_tiers, seed, output_dir, llm_mode) keep the defaults",
        "# in qaura/config.py.",
        "#",
        "# Review, then either:  qaura run --config qaura.generated.yaml",
        "#                 or:   copy it over qaura.yaml yourself.",
        "# `qaura init` never writes to qaura.yaml.",
    ])
    return "\n".join(lines)


def _render_invariant_entry(verdict: CandidateVerdict, commented: bool) -> str:
    inv = verdict.invariant
    payload = {
        "name": inv.name,
        "description": inv.description,
    }
    if inv.container_selector:
        payload["container_selector"] = inv.container_selector
    payload["values"] = dict(inv.values)
    payload["expression"] = inv.expression

    body = yaml.safe_dump([payload], sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=WRAP_WIDTH).rstrip("\n")
    if commented:
        body = "\n".join(f"# {line}" if line.strip() else "#" for line in body.split("\n"))
    return body


def render_invariants(verdicts: list[CandidateVerdict]) -> str:
    active = [v for v in verdicts if v.status == "accepted" and v.confidence != "low"]
    weak = [v for v in verdicts if v.status == "accepted" and v.confidence == "low"]
    violated = [v for v in verdicts if v.status == "rejected_violated"]
    unverified = [v for v in verdicts if v.status == "unverified"]

    lines = [
        "# invariants — confidence: per-rule, see each entry",
        "#   Business rules checked after every action. These are the only detector that can",
        "#   catch a bug where nothing crashes and no request fails — a total that goes stale",
        "#   after a coupon, a count that stops matching its rows.",
    ]

    if not active:
        lines.append("invariants: []")
    else:
        lines.append("invariants:")
        for verdict in active:
            lines.extend(_comment_block(
                f"{verdict.invariant.name} — confidence: {verdict.confidence}; "
                f"selectors: {verdict.durability}. {verdict.reason}.",
                indent="  ", bullet="# ",
            ))
            if verdict.selector_kinds:
                detail = ", ".join(
                    f"{name}={verdict.selector_kinds.get(name, '?')}"
                    f"/{verdict.selector_scores.get(name, 0)}"
                    for name in sorted(verdict.selector_kinds)
                )
                lines.extend(_comment_block(f"selector kind/score: {detail}",
                                            indent="  ", bullet="# "))
            body = _render_invariant_entry(verdict, commented=False)
            lines.append(textwrap.indent(body, "  "))

    if weak:
        lines.extend([
            "",
            "# --- accepted, but on a single observation ------------------------------------",
            "#   Each of these held everywhere it could be evaluated, but that was only one",
            "#   page. Commented out because one data point is a coincidence until it isn't.",
        ])
        for verdict in weak:
            lines.extend(_comment_block(f"{verdict.invariant.name}: {verdict.reason}.", bullet="#   "))
            lines.append(_render_invariant_entry(verdict, commented=True))

    if violated:
        lines.extend([
            "",
            "# --- REJECTED: violated during recon ------------------------------------------",
            "#   These did NOT hold on at least one page. That means one of two things, and it",
            "#   is worth knowing which before deleting them: either the rule is wrong, or the",
            "#   rule is right and the app already has this bug.",
        ])
        for verdict in violated:
            detail = (
                f"{verdict.invariant.name}: {verdict.reason}. "
                f"First violation at {verdict.violating_state_url}. "
                f"Observed values: {verdict.sample_values}."
            )
            lines.extend(_comment_block(detail, bullet="#   "))
            lines.append(_render_invariant_entry(verdict, commented=True))

    if unverified:
        lines.extend([
            "",
            "# --- unverified: never evaluable ----------------------------------------------",
            "#   Recon never reached a page where these could be checked, so they are neither",
            "#   confirmed nor refuted. The usual cause is a rule that only applies on a page",
            "#   behind a login or a few clicks deep. Uncomment after checking the selectors.",
        ])
        for verdict in unverified:
            lines.extend(_comment_block(
                f"{verdict.invariant.name}: {verdict.reason}.", bullet="#   "
            ))
            lines.append(_render_invariant_entry(verdict, commented=True))

    return "\n".join(lines)


def render_config(proposal: ConfigProposal) -> str:
    blocks = [render_header(proposal.header)]
    blocks.extend(render_field(f) for f in proposal.fields)
    blocks.append(render_invariants(proposal.verdicts))
    return "\n\n".join(blocks) + "\n"


def assert_loadable(rendered: str) -> None:
    """The correctness gate. Re-parses the emitter's own output, constructs a real
    QAuraConfig from it, and re-runs every active invariant expression through the
    engine's own validator.

    This exists because the failure it prevents is invisible at write time and loud
    later: a quoting bug produces a file that looks fine and that load_config() refuses
    on the user's next run, by which point the recon that produced it is gone.
    """
    from qaura.core.invariants import InvariantError, evaluate_expression
    from qaura.init.infer import validate_proposal_loads

    config = validate_proposal_loads(rendered)

    for invariant in config.invariants:
        try:
            evaluate_expression(invariant.expression, {name: 1.0 for name in invariant.values})
        except InvariantError as e:
            raise ValueError(
                f"generated invariant {invariant.name!r} has an expression the engine rejects: {e}"
            ) from e


def write_generated(rendered: str, path: Path, *, force: bool = False) -> Path:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists — pass --force to overwrite it")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    return path
